use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'VoiceRoomRequest_Example' do
  pod 'VoiceRoomRequest', :path => '../'

  target 'VoiceRoomRequest_Tests' do
    inherit! :search_paths

    
  end
end
